### PR TITLE
Added SLSQP minimizer and fixed unittests

### PR DESCRIPTION
**Pull request by nightvision04**
- Boosted indicator speed by 4-10x
- Boosted lppls.minimize() speeds by at least 25x
- Fixed unittests

### CODE REVIEW

**Comment by nightvision04** [comment]
@Joshwani Just so you know, I tested this change for stability between datasets. I flagged the same zones after changing the minimizer function. It is so blazing fast. Using it on my local branch and it really is incredible. Showed me where the new bottlenecks are to work on.

**Comment by nightvision04** [comment]
I'm glad I wrote unittests beforehand, haha!

**Comment by nightvision04** [comment]
@Joshwani  With this branch, I get the fastest speeds by setting n_workers=1

**Comment by nightvision04** [comment]
@Joshwani 

I've noticed that the SLSQP method, on average requires far fewer searches Nelder-Mead.  

This has me a bit concerned, because it means that "condition 1" will be flagged far more often with SLSQP. 

Since SLSQP agrees with Nelder-Mead's solution (when found), I am not too concerned that we are failing to meet assumptions.

Was there a particular reason that you have been using Nelder-Mead?

**Comment by nightvision04** [comment]
Also - this branch shouldn't produce any merge conflicts with the numba branch, in case you are concerned.

**Comment by Joshwani** [comment]
This is great stuff @nightvision04!

**Pull request merged**
